/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import model.Community;
import model.Patient;
import model.VitalSigns;

/**
 *
 * @author pridh
 */
public class CreateVitalSignsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVitalSignsJPanel
     */
    public CreateVitalSignsJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtTemperature = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        txtPulse = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Record Patient's Vitals");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 41, 700, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Patient ID :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 121, 115, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Temperature :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 154, 115, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Blood Pressure :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 192, 115, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Pulse :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 230, 115, -1));
        add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 119, 150, -1));
        add(txtTemperature, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 155, 150, -1));
        add(txtBloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 193, 150, -1));
        add(txtPulse, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 231, 150, -1));

        btnSave.setBackground(new java.awt.Color(102, 102, 102));
        btnSave.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 10)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 268, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ArrayList<VitalSigns> arr = new ArrayList<>();
        Community community;
        boolean exists = false;
        Map<Patient, ArrayList<VitalSigns>> history = Patient.getEncounters();
        VitalSigns vitals;
        Patient patient = new Patient();
        int age = 0;
        for (Patient p : history.keySet()) {
            if (Integer.parseInt(txtPatientID.getText()) == p.getId()) {
                arr = history.get(p);
                exists = true;
                patient = p;
            }
        }
        if (exists) {
            vitals = new VitalSigns();
            vitals.setDate(LocalDateTime.now());
            vitals.setBloodPressure(Double.parseDouble(txtBloodPressure.getText()));
            vitals.setTemperature(Double.parseDouble(txtTemperature.getText()));
            vitals.setPulse(Integer.parseInt(txtTemperature.getText()));
            arr.add(vitals);
            history.put(patient, arr);
            JOptionPane.showMessageDialog(btnSave, "VItal Signs Successfully Recorded for the patient");
        } else {
            JOptionPane.showMessageDialog(btnSave, "Patient with given ID does not exists");
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPulse;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
