/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import model.Community;
import model.Patient;
import model.VitalSigns;

/**
 *
 * @author pridh
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    public CreatePatientJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblPatientID = new javax.swing.JLabel();
        lblPatientAge = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblCommunityName = new javax.swing.JLabel();
        lblCommunityID = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblHouseNo = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtPatientID = new javax.swing.JTextField();
        txtPatientAge = new javax.swing.JTextField();
        txtPatientDob = new javax.swing.JTextField();
        txtCommunityName = new javax.swing.JTextField();
        txtCommunityID = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtHouseNo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Patient Record");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 680, -1));

        lblPatientName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPatientName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientName.setText("Patient Name :");
        add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 73, 120, -1));

        lblPatientID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPatientID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientID.setText("Patient ID :");
        add(lblPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 103, 120, -1));

        lblPatientAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPatientAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPatientAge.setText("Patient Age :");
        add(lblPatientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 133, 120, -1));

        lblDOB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDOB.setText("Date Of Birth :");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 163, 120, -1));

        lblCommunityName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCommunityName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCommunityName.setText("Community Name :");
        add(lblCommunityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 193, 147, -1));

        lblCommunityID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCommunityID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCommunityID.setText("Community ID :");
        add(lblCommunityID, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 223, 120, -1));

        lblCity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City :");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 253, 120, -1));

        lblHouseNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHouseNo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHouseNo.setText("House No. :");
        add(lblHouseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 283, 120, -1));
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 74, 150, -1));
        add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 104, 150, -1));
        add(txtPatientAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 134, 150, -1));
        add(txtPatientDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 164, 150, -1));

        txtCommunityName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityNameActionPerformed(evt);
            }
        });
        add(txtCommunityName, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 194, 150, -1));
        add(txtCommunityID, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 224, 150, -1));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 254, 150, -1));
        add(txtHouseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 284, 150, -1));

        btnSave.setBackground(new java.awt.Color(102, 102, 102));
        btnSave.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 10)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 321, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommunityNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        boolean flag = false;
        
        flag = fireValidations();

        Patient patient;
        boolean exists;
        Community community;

        patient = new Patient();
        ArrayList<VitalSigns> arr = new ArrayList<VitalSigns>();
        Map<Patient, ArrayList<VitalSigns>> history = Patient.getEncounters();
        exists = false;
        
        if (flag) {
            for (Patient p : history.keySet()) {
                if (Integer.parseInt(txtPatientID.getText()) == p.getId()) {
                    exists = true;
                    arr = history.get(p);
                    patient = p;
                }
            }
            
            if (!exists) {
                community = new Community();
                community.setId(Integer.parseInt(txtCommunityID.getText()));
                community.setCity(txtCity.getText());
                community.setName(txtCommunityName.getText());
                community.setHouseNo(txtHouseNo.getText());
                String dob = txtPatientDob.getText();

                patient.setAge(Integer.parseInt(txtPatientAge.getText()));
                patient.setBirthDate(dob);
                patient.setId(Integer.parseInt(txtPatientID.getText()));
                patient.setName(txtPatientName.getText());
                patient.setCommunity(community);
                history.put(patient, arr);
                JOptionPane.showMessageDialog(btnSave, "patient encounter created successfully");
            } else {
                JOptionPane.showMessageDialog(btnSave, "Patient already exists!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please verify all the fields");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private boolean fireValidations() {
        boolean valid = true;

        if (!txtPatientName.getText().matches("^[a-zA-Z]*$") || (txtPatientName.getText() == null) || (txtPatientName.getText().length() == 0)) {
            txtPatientName.setBackground(Color.red);
            valid = false;
        } else {
            txtPatientName.setBackground(Color.white);
        }
        
        if (!txtPatientID.getText().matches("^[0-9]+$") || (txtPatientID.getText() == null) || (txtPatientID.getText().length() == 0)) {
            txtPatientID.setBackground(Color.red);
            valid = false;
        } else {
            txtPatientID.setBackground(Color.white);
        }

        if (!txtPatientDob.getText().matches("^([0-2][0-9]||3[0-1])/(0[0-9]||1[0-2])/([0-9][0-9])?[0-9][0-9]$") || (txtPatientDob.getText() == null) || (txtPatientDob.getText().length() == 0)) {
            txtPatientDob.setBackground(Color.red);
            valid = false;
            JOptionPane.showMessageDialog(this, "Please enter date in DD/MM/YYYY format");
        } else {
            txtPatientDob.setBackground(Color.white);
        }

        if (!txtPatientAge.getText().matches("^[0-9]{1,3}$") || (txtPatientAge.getText().length() == 0)) {
            txtPatientAge.setBackground(Color.red);
            valid = false;
        } else {
            txtPatientAge.setBackground(Color.white);
        }
        
        if (!txtCommunityName.getText().matches("^[a-zA-Z]*$") || (txtCommunityName.getText() == null) || (txtCommunityName.getText().length() == 0)) {
            txtCommunityName.setBackground(Color.red);
            valid = false;
        } else {
            txtCommunityName.setBackground(Color.white);
        }
        
        if (!txtCommunityID.getText().matches("^[0-9]+$") || (txtCommunityID.getText() == null) || (txtCommunityID.getText().length() == 0)) {
            txtCommunityID.setBackground(Color.red);
            valid = false;
        } else {
            txtCommunityID.setBackground(Color.white);
        }
        
        if (!txtCity.getText().matches("^[a-zA-Z]*$") || (txtCity.getText() == null) || (txtCity.getText().length() == 0)) {
            txtCity.setBackground(Color.red);
            valid = false;
        } else {
            txtCity.setBackground(Color.white);
        }
        
        if (!txtHouseNo.getText().matches("^[a-zA-Z0-9]*$") || (txtHouseNo.getText() == null) || (txtHouseNo.getText().length() == 0)) {
            txtHouseNo.setBackground(Color.red);
            valid = false;
        } else {
            txtHouseNo.setBackground(Color.white);
        }
        
        return valid;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunityID;
    private javax.swing.JLabel lblCommunityName;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblHouseNo;
    private javax.swing.JLabel lblPatientAge;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunityID;
    private javax.swing.JTextField txtCommunityName;
    private javax.swing.JTextField txtHouseNo;
    private javax.swing.JTextField txtPatientAge;
    private javax.swing.JTextField txtPatientDob;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
